name: "yolo"
backend: "onnxruntime"
max_batch_size: 16

input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [ 3, -1, -1 ]  # → [batch, 3, H, W]
  }
]

output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [ -1, -1 ]  # 2 dims! → [batch, 84, 8400]
  }
]
